### ISSUE TITLE
fix readme images

### ISSUE THREAD

**Issue by sckott** [ropensci/rplos#114]
> It was recently pointed out to us that some README.html files (generated
from the corresponding README.md ones) on the CRAN package web pages are
incomplete, missing 'local' images not available from the web page and
in most cases actually not even shipped with the package.  This clearly
should be changed, so we will move to using '--self-contained' for the
pandoc conversion to ensure that the README.html files are "complete".

> Of course, this implies that all 'local' images used in README.md are
needed in the package sources.

> If the images are also used for vignettes or Rd files, you can put them
in the 'vignettes' or 'man/figures' directories.  Otherwise, please put
them in the top-level 'tools' directory, or a subdirectory of it.

> The CRAN incoming checks in r-devel were changed to perform the pandoc
conversion checks with '--self-contained', and hence will warn about
missing images.

> Pls ensure completeness in the next regular update of your package.

************************************************************************

```
$`/data/rsync/PKGS/rplos/README.md`
[1] "inst/assets/img/highbrow.png"
[2] "inst/assets/img/unnamed-chunk-21-1.png"
```

**Comment by amrrs** [comment]
Hi @sckott, Just trying to understand. The places where image is missing in readme.html has to be fixed with the images copied from vignette? Sorry, If i'm wrong. Could you please elaborate?

**Comment by sckott** [comment]
👋  @amrrs  - thanks for your question. 

The task is to make a directory called `tools`, then move those two images listed above into that folder, then change the path to those image files in both the `README.Rmd` and `README.md` files

let me know if you need additional help!

**Comment by sckott** [comment]
done in #116
