### ISSUE TITLE
Indicate that internal pagination is implemented in docs

### ISSUE THREAD

**Issue by Bubblbu** [ropensci/rplos#122]
Maybe it would be good to indicate that internal looping is implemented in the documentation for searchplos. I think that this threw me off and made me assume that manual looping is required:

> start -- Record to start at (used in combination with limit when you need to cycle through more results than the max allowed=1000)

**Comment by sckott** [comment]
install like `remotes::install_github("ropensci/rplos@progress")` e.g.

```r
res <- searchplos(q='*:*', limit = 2000, progress = httr::progress())
```

**Comment by Bubblbu** [comment]
```
Error in curl::curl_fetch_memory(x$url$url, handle = x$url$handle) : 
  Illegal characters found in URL
```

**Comment by sckott** [comment]
are you sure you installed from the `progress` branch and you restarted your R session, etc
