### ISSUE TITLE
Phrase searching request

### ISSUE THREAD

**Issue by poldham** [ropensci/rplos#96]
Hi Scott, 

Very many thanks to you and the other authors for the package and the tutorial. I have been following the tutorial and attempting to expand on it using "synthetic biology" as my basic search criteria (I was lead author on this http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0034368 , hence my interest):

searchplos(q = "synthetic biology", fl = "id"). 

However, this is returning 18,627 DOIs which can't be right for the phrase in PLOS and suggests that the query is running on the individual words rather than the phrase.

I tried using highplos to test this: 

highplos(q ='synthetic biology', hl.fl = 'abstract', rows=10)
highbrow(out) 

and that confirms that it is searching on single words. The api message is: 

http://api.plos.org/search?wt=json&q=synthetic biology&start=0&rows=10&hl=true&hl.fl=abstract

Possibly inserting a + might be a solution:

out <- highplos(q ='synthetic+biology', hl.fl = 'abstract', rows=10)
highbrow(out)

That seems to work. Checking through the examples for the package they all seem to use single words. It would be really helpful maybe for a future update to have phrase based searching and query construction (this would also help on subject areas). That would also allow for easy cross-testing with results from Web of Science on the same query for PLOS (using a tool like VantagePoint). While they won't ever exactly match it would be good for ball park validation. 

As a separate issue, the text fragments are great. I'm not sure from the code but a useful concordancing approach from corpus linguistics would be a fragment reading from full stop to full stop to capture a sentence as the context for the search term for further analysis. That would appeal to linguists and those interested in the context rather that retrieving results per se. That is more of an aside on possible parameters for highbrow for the future. 

Many thanks again and apologies in advance if I have missed something blindingly obvious!

Best regards, 

Paul

**Comment by sckott** [comment]
Thanks for this @poldham !

It looks like the web interface behaves the same way as the default behavior for this pacakge:

<img width="1051" alt="screen shot 2015-09-18 at 10 06 39 am" src="https://cloud.githubusercontent.com/assets/577668/9965732/19258ab4-5ded-11e5-9df0-fde2b2105dcb.png">

For searching phrases, you should be able to simply use double quotes on the phrase you're searching for. e.g., 

```r
searchplos(q ='"synthetic biology"', limit=0)
#> $meta
#>   numFound start maxScore
#> 1      982     0       NA
```

And that matches what happens in the PLOS web interface if you quote the phrase

I don't think I have any documentation on this in the package - I'll add that, see #97

> ...a useful concordancing approach from corpus linguistics would be a fragment reading from full stop to full stop to capture a sentence as the context for the search term for further analysis. 

There may be a way to do this with parameters in the functions here. I poked around a bit, haven't found anything yet. you can use `hl.fragsize` to set the number of characters to return in the fragment, but that isn't smart enough to get just the sentence. It looks like there are things you can do with the Solr configuration to help with this, but I don't think we're likely to convince PLOS to do this. I'll ask about this though and see what they say. https://groups.google.com/forum/#!topic/plos-api-developers/44B-pGZJtU0

**Comment by sckott** [comment]
see also #98

**Comment by poldham** [comment]
Dear Scott, 

Many thanks for this message and apologies also for my delayed response.

The double quote approach works very well for searching using phrases. On searches by section e.g. plostitle() etc it seemed to me that the single quotes worked fine. 

On concordancing. I think that highplos() combined with hl.fragsize is really useful. I also liked hl.snippets although I think it can be a little difficult to understand what precisely is happening with snippets. 

I will respond under #98 <https://github.com/ropensci/rplos/issues/98> on the sentence match concordancing issue. It is possible that the qdap package sentSplit() function provides a solution (based on a defunkt version of openNLP sentDetect()). However, this requires some more digging and there may be other options in tm. 

I am presently writing the WIPO Manual on Open Source Patent Analytics (aimed at researchers working on patents in developing countries). I have written an indepth walkthrough for rplos for complete beginners in R that can now be found on rpubs as a working draft: http://rpubs.com/poldham/rplos <http://rpubs.com/poldham/rplos> . I include a couple of small functions that may or may not be useful or that might inspire some better ideas. I suspect that some of these functions may be covered in the fulltext() documentation and I am moving on to that next.

What I really like about rplos as a tool for introducing R and working with APIs (for beginners like me) is that it is easy to use and it is not a nightmare to process the results into workable tables(!)

Best regards and thanks again,

Paul

**Comment by sckott** [comment]
Great, glad it works. You all sorted now @poldham ?

**Comment by sckott** [comment]
assuming this works fine now, closing
